[programs.localnet]
forum = "CcssQs9DoZFQUq2nUygcFxKVFZUPvdsux7pBE9dqa2YH"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "https://lingering-lingering-mountain.solana-devnet.quiknode.pro/fbbd36836095686bd9f580212e675aaab88204c9/"
wallet = "/Users/nathanshirley/.config/solana/id.json"

[scripts]
test = "ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts"