[programs.localnet]
zine = "GwMnqrRGaxWHJzu1vqzdssLjJfkM6jbLxAG8WekGwUjY"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/nathanshirley/.config/solana/id.json"

[scripts]
test = "ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts"
