[programs.localnet]
forum = "CcssQs9DoZFQUq2nUygcFxKVFZUPvdsux7pBE9dqa2YH"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/nathanshirley/.config/solana/id.json"

[scripts]
test = "ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts"